package airlines;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.*;
import java.text.*;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.SystemColor;
import java.awt.Font;
import javax.swing.UIManager;
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balup
 */
//public class String Name[4];
public class addPassenger extends javax.swing.JInternalFrame {

    /**
     * Creates new form addPassenger
     */
    String FlightNo="",UID="";
    int seats=0;
    int pno=0;
    static String t;
    public addPassenger(String str) {
    	t=new String(str);
        initComponents();
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        jLabel12.setVisible(true);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
    }
    public addPassenger() {
    	getContentPane().setBackground(Color.YELLOW);
    	//setIcon(true);
    	setFrameIcon(new ImageIcon(addPassenger.class.getResource("/images/ficon1.png")));
        initComponents();
        
       
    }
    
    Connection con;
    
    PreparedStatement pst,pn;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(SystemColor.activeCaption);
        txtsource = new javax.swing.JComboBox<>();
        txtsource.setBackground(UIManager.getColor("activeCaption"));
        txtsource.setFont(new Font("Tahoma", Font.PLAIN, 11));
        txtdeparture = new javax.swing.JComboBox<>();
        txtdeparture.setBackground(UIManager.getColor("activeCaption"));
        txtdeparture.setFont(new Font("Tahoma", Font.PLAIN, 11));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 11));
        jButton3 = new javax.swing.JButton();
        jButton3.setBackground(new Color(119, 136, 153));
        jButton3.setFont(new Font("Tahoma", Font.BOLD, 10));
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.BOLD, 11));
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setViewportBorder(UIManager.getBorder("Table.scrollPaneBorder"));
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton1.setForeground(SystemColor.controlText);
        jButton1.setBackground(new Color(119, 136, 153));
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 10));
        jButton2 = new javax.swing.JButton();
        jButton2.setForeground(SystemColor.controlText);
        jButton2.setBackground(new Color(119, 136, 153));
        jButton2.setFont(new Font("Tahoma", Font.BOLD, 10));
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select City", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtsource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Hyderabad", "Chennai", "Banglore", "Mumbai" }));

        txtdeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Hyderabad", "Chennai", "Banglore", "Mumbai", " " }));

        jLabel1.setText("Source*");

        jLabel2.setText("Departure*");

        jLabel3.setText("Date*");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jLabel6.setText("No of seats*");

        jLabel7.setFont(new Font("Tahoma", Font.ITALIC, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Please select a city");

        jLabel8.setFont(new Font("Tahoma", Font.ITALIC, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Please select a city");

        jLabel9.setFont(new Font("Tahoma", Font.ITALIC, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Please select an upcoming date");

        jLabel10.setFont(new Font("Tahoma", Font.ITALIC, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("This should be positive");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jLabel1)
        				.addComponent(txtsource, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(txtdeparture, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel3)
        				.addComponent(jDateChooser1, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(182)))
        					.addGap(10))
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
        					.addComponent(jButton3)
        					.addGap(53))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel2)
        					.addComponent(jLabel6))
        				.addComponent(jLabel3))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(txtsource, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtdeparture, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jDateChooser1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel7)
        						.addComponent(jLabel8)
        						.addComponent(jLabel9)
        						.addComponent(jLabel10)))
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jButton3)))
        			.addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);
        jTable1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleBackground"));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fno", "Source", "Departure", "Date", "Start_time", "End_time", "Total_seats", "Seats_available", "Fare"
            }
            /*boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };*/

            /*public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }*/
    ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("No Flights Found");

        jLabel12.setText("* Reqired Fields");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap(533, Short.MAX_VALUE)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        					.addGap(24))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(535)
        							.addComponent(jLabel12))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(29)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 663, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 663, GroupLayout.PREFERRED_SIZE))))
        					.addGap(0, 3, Short.MAX_VALUE)))
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(0, 321, Short.MAX_VALUE)
        			.addComponent(jLabel5)
        			.addGap(281))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(21, Short.MAX_VALUE)
        			.addComponent(jLabel12)
        			.addGap(2)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel5)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE)
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlines","root","Surya72");
            con.setAutoCommit(false);
            //Statement stmt = con.createStatement();
            pn = con.prepareStatement("select *  from user_flight where uid=? and fno=?");
            //ResultSet rs = stmt.executeQuery("select *  from user_flight where uid=? and fno=?");
             pn.setString(1, UID);
             pn.setString(2, FlightNo);
              //rs.last();
             ResultSet rss = pn.executeQuery();
             //rss.next();
             //pno = rss.getInt(1);
             while(rss.next()){
                 pno++;
             }
                Details d = new Details(UID,FlightNo,seats,pno+1,t);
                if(!"".equals(FlightNo)) {
                    JDesktopPane dp = getDesktopPane();
                    dp.add(d);
                    d.setVisible(true);
                    setVisible(false);
        } else JOptionPane.showMessageDialog(null,
                "Please select a flight",
                "ERROR",
                JOptionPane.WARNING_MESSAGE);
    }
        catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(addPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
          FlightNo = Df.getValueAt(selectIndex, 0).toString().trim();
          UID = t;
    }                                    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        setVisible(false);
        
        
        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

        String arrival ;
        String departure ;
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
       
        //String date = (jDateChooser1.getDateEditor().getUiComponent()).getText();
        String date;
        if( !(txtsource.getSelectedItem().toString().trim().isEmpty())) {arrival =  txtsource.getSelectedItem().toString().trim(); jLabel7.setVisible(false);
        if( !(txtdeparture.getSelectedItem().toString().trim().isEmpty())) {departure =  txtdeparture.getSelectedItem().toString().trim(); jLabel8.setVisible(false);
        if( !(dFormat.format(jDateChooser1.getDate()).compareTo(java.time.LocalDate.now().toString())<=0)) { date = dFormat.format(jDateChooser1.getDate()); jLabel9.setVisible(false);
        if((Integer)jSpinner1.getValue()>0) {  seats = (Integer)jSpinner1.getValue(); jLabel10.setVisible(false);
        
        try {
            //System.out.println("Connecting to a selected database.22222222222..");
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("Connecting to a selected database...");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlines","root","Surya72");
            con.setAutoCommit(false); 
            Savepoint savePoint = con.setSavepoint("mysavepoint");
            pst = con.prepareStatement("select * from flight where arrival=? and departure=? and date=?");
            pst.setString(1, arrival);
            pst.setString(2, departure);
            pst.setString(3, date);
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rsm = rs.getMetaData();
            int c;
            c = rsm.getColumnCount();

            /*jTable1.getRowCount();
            /* if(r==0){
                jLabel5.setVisible(true);
            }
            else jLabel5.setVisible(false);*/

            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            int r=0;
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i = 1;i<=c;i++){
                    v2.add(rs.getString("Fno"));
                    v2.add(rs.getString("arrival"));
                    v2.add(rs.getString("departure"));
                    v2.add(rs.getDate("Date"));
                    v2.add(rs.getTime("start_time"));
                    v2.add(rs.getTime("end_time"));
                    v2.add(rs.getInt("total_seats"));
                    v2.add(rs.getInt("no_of_seats_available"));
                    v2.add(rs.getInt("fare"));

                }
                Df.addRow(v2);
                r++;

            }
            if(r==0){
                jLabel5.setVisible(true);
            }
            else jLabel5.setVisible(false);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(addPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else jLabel10.setVisible(true);
        }
        else jLabel9.setVisible(true);
        }
        else jLabel8.setVisible(true);

    }                                        
        else jLabel7.setVisible(true);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> txtdeparture;
    private javax.swing.JComboBox<String> txtsource;
    // End of variables declaration                   
}
